# Generated by Django 4.2.13 on 2024-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
