# Generated by Django 4.2.13 on 2024-06-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_document_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('book', 'Book'), ('youtube', 'Youtube Transcript'), ('audio', 'Audio Transcript'), ('news', 'News')], default='book', max_length=30),
        ),
    ]
